import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: "100%",
    height: "100%",
  },
  searchContainer: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 1000,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    fontSize: 16,
    color: "#000",
    paddingVertical: 0,
  },
  suggestionsContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    marginTop: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  suggestionItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  suggestionText: {
    fontSize: 15,
    color: "#333",
  },
  nextStepRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  nextStepText: {
    fontSize: 13,
    color: "#5F6368",
    flexShrink: 1,
  },
  laneGuidanceRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  lanesStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  lanePill: {
    width: 26,
    height: 10,
    borderRadius: 6,
    backgroundColor: "#E8EAED",
  },
  lanePillActive: {
    backgroundColor: "#1A73E8",
  },
  laneHintText: {
    fontSize: 13,
    color: "#5F6368",
    fontWeight: "600",
  },
  arrowMarker: {
    width: 60,
    height: 60,
    backgroundColor: "#fff",
    opacity: 0.98,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#E8EAED",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  rightButtonsContainer: {
    position: "absolute",
    right: 16,
    flexDirection: "column",
    gap: 12,
  },
  myLocationButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  myLocationButtonActive: {
    backgroundColor: "#E8F0FE",
  },
  cameraDebugToggle: {
    width: 48,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#111",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 6,
  },
  cameraDebugToggleText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  cameraDebugPanel: {
    position: "absolute",
    width: 260,
    backgroundColor: "rgba(17, 17, 17, 0.92)",
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 12,
  },
  cameraDebugHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  cameraDebugTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
  },
  cameraDebugLine: {
    color: "#fff",
    fontSize: 12,
    opacity: 0.92,
    marginBottom: 4,
  },
  cameraDebugButtonsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  cameraDebugButton: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraDebugButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  cameraDebugHint: {
    color: "#fff",
    fontSize: 11,
    opacity: 0.75,
    marginTop: 10,
  },
  stopsButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  statsButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  startNavigationButton: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4285F4",
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  stopNavigationButton: {
    backgroundColor: "#EA4335",
  },
  startNavigationText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 8,
  },
  instructionPanel: {
    position: "absolute",
    left: 16,
    right: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
  },
  instructionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  instructionContent: {
    flex: 1,
    marginLeft: 12,
  },
  distanceText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#4285F4",
    marginBottom: 4,
  },
  instructionText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "600",
  },
  arrivalText: {
    fontSize: 22,
    fontWeight: "700",
    color: "#34A853",
    marginBottom: 4,
  },
  arrivalSubtext: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  speedContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  currentSpeed: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  speedValue: {
    fontSize: 32,
    fontWeight: "700",
    color: "#333",
  },
  speedUnit: {
    fontSize: 16,
    color: "#666",
    marginLeft: 4,
  },
  speedLimitCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 4,
    borderColor: "#EA4335",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  speedLimitText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#EA4335",
  },
  headingDisplay: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  headingValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  etaContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  etaText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
  },
  nextStopButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34A853",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 12,
    gap: 8,
    justifyContent: "center",
  },
  nextStopButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  stageInfo: {
    position: "absolute",
    left: 16,
    right: 16,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  stageText: {
    color: "#4CAF50",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 4,
  },
  stageSubtext: {
    color: "#fff",
    fontSize: 12,
    opacity: 0.8,
  },
  stopMarker: {
    width: 32,
    height: 32,
    backgroundColor: "#4285F4",
    borderRadius: 16,
    borderWidth: 3,
    borderColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  stopMarkerText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  stopsBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#EA4335",
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  stopsBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  stopsPanel: {
    position: "absolute",
    left: 16,
    right: 16,
    maxHeight: 300,
    backgroundColor: "#fff",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
  },
  stopsPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  stopsPanelTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
  },
  stopsList: {
    maxHeight: 200,
  },
  stopItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
    backgroundColor: "#fff",
  },
  stopItemDragging: {
    backgroundColor: "#f9f9f9",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  stopItemNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#4285F4",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  destinationNumber: {
    backgroundColor: "#EA4335",
  },
  stopItemNumberText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  stopItemAddress: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  stopItemActions: {
    flexDirection: "row",
    gap: 8,
  },
  stopItemButton: {
    padding: 4,
  },
  stopsPanelFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  stopsPanelHint: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
});
